#!/bin/sh
CURDIR=$(cd $(dirname ${BASH_SOURCE[0]});  cd ../../; pwd )
echo $CURDIR
echo "正在进行 lint 代码检测"
$CURDIR/./gradlew lintCheck -PisLintCheck
if [ $? -eq 0   ]; then
    echo "代码检测通过"
else
    exit 1
fi